runtime: python
env: flex
service: flex-schedule
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
  python_version: 2
manual_scaling:
  instances: 1

env_variables:
  PROJECT_ID: providence-demo
  LOCATION: global
  KEYRING: storage
  KEY: mykey
  ENCRYPTED_BUCKET: mdh-prov-enc-bucket
  SECRET: dark-sky-key
  WEATHER_BUCKET: mdh-weather-bucket
